import {
  ApartmentOutline,
  AppstoreOutline,
  BankOutline,
  BarChartOutline,
  DatabaseOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  EnvironmentOutline,
  FilePdfOutline,
  FormOutline,
  DashboardOutline,
  HistoryOutline,
  LoginOutline,
  LogoutOutline,
  MessageOutline,
  SearchOutline,
  SettingOutline,
  TagsOutline,
  TeamOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  ApartmentOutline,
  AppstoreOutline,
  BankOutline,
  BarChartOutline,
  DashboardOutline,
  DatabaseOutline,
  EnvironmentOutline,
  FilePdfOutline,
  FormOutline,
  HistoryOutline,
  LoginOutline,
  LogoutOutline,
  MessageOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  SearchOutline,
  SettingOutline,
  TagsOutline,
  TeamOutline,
  UserOutline
];
