const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outputDir = path.join(rootDir, 'src', 'environments');
const outputPath = path.join(outputDir, 'environment.ts');

function parseEnv(content) {
  return content.split(/\r?\n/).reduce((values, line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return values;
    }

    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) {
      return values;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
    return values;
  }, {});
}

const env = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : {};
const backendUrl = (env.BACKEND_URL || 'http://localhost:8000').replace(/\/+$/, '');

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(
  outputPath,
  `// This file is generated by scripts/generate-env.js from .env.\n` +
    `export const environment = {\n` +
    `  backendUrl: ${JSON.stringify(backendUrl)},\n` +
    `  apiUrl: ${JSON.stringify(`${backendUrl}/api`)}\n` +
    `};\n`
);

console.log(`Environment generated with BACKEND_URL=${backendUrl}`);
